### ISSUE TITLE
Ficheros de configuración del IDE

### ISSUE THREAD

**Issue by cr0hn** [CyberWatcherOrg/SSOP#13]
No es buena práctica subir a GIT los ficheros de configuración del IDE:

<img width="513" alt="ssop_ssop_at_master_ _cyberwatcherorg_ssop" src="https://user-images.githubusercontent.com/4076390/49295450-177b9380-f4b6-11e8-92b1-fb6df4ecb2a4.png">

**Comment by sfaci** [comment]
Se han dejado de mantener esas carpetas en el repositorio. Ocurría en otra de las webapps
