### ISSUE TITLE
Localizar dispositivo lector de huellas

### ISSUE THREAD

**Issue by CyberWatcherZgZ** [CyberWatcherOrg/SSOP#3]
En SSOP necesitamos un lector de huellas digital usb. El lector debe permitir realizar lectura de la huella a través de java y librería.

Localizar el dispositivo en Amazon.

**Comment by miguelangelcw** [comment]
Finalmente el dispositivo se ha adquirido en distribuidor TSIMPLIFICA. En el día de hoy jueves 29/11/2018 se va a recibir el envío en el hotel.

@ALL, en cuanto volvamos, podemos empezar las pruebas de lectura y encriptación de la huella para su envio al sistema central.

**Comment by miguelangelcw** [comment]
El dispositivo funciona.
