### ISSUE TITLE
Investigar envio SMS

### ISSUE THREAD

**Issue by miguelangelcw** [CyberWatcherOrg/SSOP#9]
Realizar investigación de elemento de autenticación SMS.

Si se ve que ésta parte deriva mucho tiempo, realizar alternativa

**Comment by sfaci** [comment]
Siempre podemos enviar un email, que es mucho más sencillo, gratis y todo el mundo puede leerlo igual que un SMS.

**Comment by JavierManriqueCW** [comment]
Ya tenemos el envio de SMS pero dejo la issue abierta en pos de revision
